### ISSUE TITLE
Questions regarding generating KENKU AEs

### ISSUE THREAD

**Issue by MENG2010** [Xinghui-Wu/CommanderMusic#6]
Dear Xinghui,

I hope this message finds you well. Recently, I recently came across your work KENKU, which could generate powerful and highly transferable black-box audio AEs. I'd like to evaluate KENKU in my current work.

I have been trying to generate **integrated command** AEs using the KENKU framework, **following the steps provided in the README**. However, I encountered an issue where the generated AEs failed to attack the undefended DeepSpeech model, even though your paper demonstrates that KENKU can bypass defenses like WaveGuard and MVP-Ear, which involve DeepSpeech. I was wondering if there are any specific configurations or settings I should be using to generate KENKU adversarial examples that have strong transferability to the DeepSpeech model. I would greatly appreciate any insights or suggestions you could provide. Additionally, if there are any common pitfalls or best practices you recommend when using KENKU to generate transferable adversarial examples, I would be very interested in learning about them.

Thank you for your time and consideration. I look forward to hearing back from you and learning more about generating effective and transferable AEs using the KENKU framework.

Best,
MENG

**Comment by MENG2010** [comment]
> Dear Xinghui,
> 
> I hope this message finds you well. Recently, I recently came across your work KENKU, which could generate powerful and highly transferable black-box audio AEs. I'd like to evaluate KENKU in my current work.
> 
> I have been trying to generate **integrated command** AEs using the KENKU framework, **following the steps provided in the README**. However, I encountered an issue where the generated AEs failed to attack the undefended DeepSpeech model, even though your paper demonstrates that KENKU can bypass defenses like WaveGuard and MVP-Ear, which involve DeepSpeech. I was wondering if there are any specific configurations or settings I should be using to generate KENKU adversarial examples that have strong transferability to the DeepSpeech model. I would greatly appreciate any insights or suggestions you could provide. Additionally, if there are any common pitfalls or best practices you recommend when using KENKU to generate transferable adversarial examples, I would be very interested in learning about them.
> 
> Thank you for your time and consideration. I look forward to hearing back from you and learning more about generating effective and transferable AEs using the KENKU framework.
> 
> Best, MENG

Nevermind, I have figured out how you handle the lambda in your code. Thanks.

**Comment by Xinghui-Wu** [comment]
@MENG2010 
Technically, we enabled the argument -p in the Python scripts to adjust lambda and defined its default value that was demonstrated effective towards most commercial ASRs.

We fine-tuned the lambda value towards each specific ASR. As for DeepSpeech and other open-source ASRs, they are not as robust as those commercial ASRs. In such cases, we recommend a smaller lambda value to enhance the attack performance (please refer to Section 5.4 for more details about the consequence of a smaller lambda value).

If you require any further information, feel free to contact me.
